### PR TITLE
Kernel attribute documentation

### PR DESCRIPTION
**Pull request by Helveg**
Let's see if it builds, it does on my mirror: https://nest-simulator-helveg.readthedocs.io/en/getset/ref_material/pynest_apis.html

### CODE REVIEW

**Review by jougs — CHANGES_REQUESTED** [review]
Could you please fix the creation of the restructured text for the docstrings as we discussed this morning?

**Comment by Helveg** [comment]
@jougs, The typehint for `recording_backends` says that it is a `List[str]` but the return value is a dict of dicts. It also does not seem to be settable, should we mark it readonly?

**Comment by Helveg** [comment]
@jougs ready for review

**Comment by jougs** [comment]
Although the exact way to set `recording_backends` is documented in the [guide on recording from the network](https://nest-simulator.readthedocs.io/en/latest/guides/record_from_simulations.html), I agree that it's a total pain and I'm really sorry for having let this out in the wild :crying_cat_face:

Your update captures the situation pretty well for now, but my fix for #1717 will also include a new way for interacting with recording backends, namely:

```python
>>> print(nest.recording_backends)
["ascii", "memory", "screen", "sionlib"]

>>> print(nest.GetDefaults("ascii"))
{}

>>> nest.SetDefaults("sionlib", {"buffer_size": 1024})
```

**Review by jougs — APPROVED** [review]
The new version looks really nice. Thanks!

**Pull request merged**
